export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';

export const PRODUCT_POST_REQUEST = 'PRODUCT_POST_REQUEST';
export const PRODUCT_POST_SUCCESS = 'PRODUCT_POST_SUCCESS';
export const PRODUCT_POST_FAIL = 'PRODUCT_POST_FAIL';

export const PRODUCTLIST_GET_REQUEST = 'PRODUCTLIST_GET_REQUEST';
export const PRODUCTLIST_GET_SUCCESS = 'PRODUCTLIST_GET_SUCCESS';
export const PRODUCTLIST_GET_FAIL = 'PRODUCTLIST_GET_FAIL';
